// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRmcmPg4BTi7W99OGO8AxFqar2uK-QYU',
    appId: '1:621960912350:web:3f53aed25029760aa7114f',
    messagingSenderId: '621960912350',
    projectId: 'aulamobile-bbe03',
    authDomain: 'aulamobile-bbe03.firebaseapp.com',
    storageBucket: 'aulamobile-bbe03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyurXZo9AE-CpAGBytFwCcZaoWdwK8UGE',
    appId: '1:621960912350:android:b5ae6d316426abf2a7114f',
    messagingSenderId: '621960912350',
    projectId: 'aulamobile-bbe03',
    storageBucket: 'aulamobile-bbe03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyWIK4Jggg1FY04ApKiDu9jMPc0gMtDro',
    appId: '1:621960912350:ios:908e7055317915e8a7114f',
    messagingSenderId: '621960912350',
    projectId: 'aulamobile-bbe03',
    storageBucket: 'aulamobile-bbe03.firebasestorage.app',
    iosBundleId: 'com.example.calculadoraNota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyWIK4Jggg1FY04ApKiDu9jMPc0gMtDro',
    appId: '1:621960912350:ios:908e7055317915e8a7114f',
    messagingSenderId: '621960912350',
    projectId: 'aulamobile-bbe03',
    storageBucket: 'aulamobile-bbe03.firebasestorage.app',
    iosBundleId: 'com.example.calculadoraNota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIRmcmPg4BTi7W99OGO8AxFqar2uK-QYU',
    appId: '1:621960912350:web:d766e64fdbab3d4ea7114f',
    messagingSenderId: '621960912350',
    projectId: 'aulamobile-bbe03',
    authDomain: 'aulamobile-bbe03.firebaseapp.com',
    storageBucket: 'aulamobile-bbe03.firebasestorage.app',
  );
}
